// generated by Google Gemini

#include <stdio.h>
#include <stdlib.h>

#define BUFFER_SIZE 1024

int main(void) {
    FILE *file_pointer;
    char *buffer;
    size_t buffer_size = BUFFER_SIZE;
    size_t bytes_read, i = 0;

    file_pointer = fopen("sample/teste.txt", "r");
    if (!file_pointer) {
        printf("Erro ao abrir o arquivo.\n");
        return 1;
    }

    buffer = malloc(buffer_size);
    if (!buffer) {
        printf("Erro de alocação de memória.\n");
        return 1;
    }

    while ((bytes_read = fread(&buffer[i], sizeof(char), BUFFER_SIZE, file_pointer)) > 0) {
        if (i + bytes_read >= buffer_size) {
            buffer_size += BUFFER_SIZE;
            buffer = realloc(buffer, buffer_size);
            if (!buffer) {
                printf("Erro de realocação de memória.\n");
                return 1;
            }
        }
        i += bytes_read;
        printf("%d\n", bytes_read);
    }

    buffer[i] = '\0';

    printf("Conteudo do arquivo:\n%s\n", buffer);

    fclose(file_pointer);
    free(buffer);

    return 0;
}
